# Default values for couchDB.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: klaemo/couchdb
  tag: 2.0.0
  pullPolicy: IfNotPresent
service:
  name: couchdb-lightblue-service
  type: NodePort
  externalPort: 5984
  internalPort: 5984
  nodePort: 30004
